export class Module {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly description?: string,
    public readonly displayOrder: number = 0,
    public readonly isActive: boolean = true,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date
  ) {}

  static create(
    name: string,
    description?: string,
    displayOrder: number = 0,
    isActive: boolean = true
  ): Module {
    return new Module(
      '', // ID will be generated by DB
      name,
      description,
      displayOrder,
      isActive
    );
  }
}

