export class Permission {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly moduleId: string,
    public readonly description?: string,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date
  ) {}

  static create(
    name: string,
    moduleId: string,
    description?: string
  ): Permission {
    return new Permission(
      '', // ID will be generated by DB
      name,
      moduleId,
      description
    );
  }
}

