export class Role {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly displayName: string,
    public readonly description?: string,
    public readonly isSystem: boolean = false,
    public readonly isActive: boolean = true,
    public readonly schoolId?: string,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date
  ) {}

  static create(
    name: string,
    displayName: string,
    description?: string,
    isSystem: boolean = false,
    schoolId?: string
  ): Role {
    return new Role(
      '', // ID will be generated by DB
      name,
      displayName,
      description,
      isSystem,
      true,
      schoolId
    );
  }
}

