export class UserStudent {
  constructor(
    public readonly id: string,
    public readonly userId: string,
    public readonly studentId: string,
    public readonly relationship?: string,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date
  ) {}

  static create(
    userId: string,
    studentId: string,
    relationship?: string
  ): UserStudent {
    return new UserStudent(
      '', // ID will be generated by DB
      userId,
      studentId,
      relationship
    );
  }
}

