import { IStudentRepository } from '../../../adapters_interface/repositories';
import { Student } from '../../../domain/entities';
import { CreateStudentInput } from '../../dtos';

export class CreateStudentUseCase {
  constructor(private studentRepository: IStudentRepository) {}

  async execute(input: CreateStudentInput, schoolId: string): Promise<Student> {
    const student = Student.create({
      id: '', // Will be generated by database
      firstName: input.firstName,
      lastName: input.lastName,
      age: input.age,
      birthDate: new Date(input.birthDate),
      certificationType: input.certificationType,
      graduationDate: new Date(input.graduationDate),
      schoolId,
      contactPhone: input.contactPhone,
      isLeveled: input.isLeveled || false,
      expectedLevel: input.expectedLevel,
      address: input.address,
      parents: input.parents?.map(p => ({ id: '', name: p.name })) || [],
    });

    return this.studentRepository.create(student);
  }
}

