import { IStudentRepository } from '../../../adapters_interface/repositories';
import { Student, CertificationType } from '../../../domain/entities';
import { CreateStudentInput } from '../../dtos';
import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';

const prisma = new PrismaClient();

export class CreateStudentUseCase {
  constructor(private studentRepository: IStudentRepository) {}

  async execute(input: CreateStudentInput, schoolId: string): Promise<Student> {
    // 1. Get STUDENT role
    const studentRole = await prisma.role.findFirst({
      where: { name: 'STUDENT', schoolId: null },
    });

    if (!studentRole) {
      throw new Error('STUDENT role not found in system');
    }

    // 2. Create User account for student
    const userId = randomUUID();
    const userEmail = `student.${userId.substring(0, 8)}@${schoolId}.alenna.io`; // Unique email
    
    const user = await prisma.user.create({
      data: {
        id: userId,
        clerkId: `student_${userId}_clerk`, // Placeholder - will be set on first login
        email: userEmail,
        firstName: input.firstName,
        lastName: input.lastName,
        schoolId,
      },
    });

    // 3. Assign STUDENT role
    await prisma.userRole.create({
      data: {
        id: randomUUID(),
        userId: user.id,
        roleId: studentRole.id,
      },
    });

    // 4. Calculate age from birthDate
    const birthDate = new Date(input.birthDate);
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }

    // 5. Create Student entity (using data from input + calculated age)
    const student = Student.create({
      id: '', // Will be generated by database
      firstName: input.firstName,
      lastName: input.lastName,
      age, // Calculated from birthDate
      birthDate,
      certificationTypeId: input.certificationTypeId,
      certificationType: new CertificationType(input.certificationTypeId, '', schoolId), // Will be populated by repository
      graduationDate: new Date(input.graduationDate),
      schoolId,
      contactPhone: input.contactPhone,
      isLeveled: input.isLeveled || false,
      expectedLevel: input.expectedLevel,
      currentLevel: input.currentLevel,
      address: input.address,
      parents: [],
    });

    // 6. Create Student record linked to User
    const createdStudent = await this.studentRepository.createWithUser(student, user.id);

    // 7. Create parent users and link them to the student (at least 1 required)
    if (!input.parents || input.parents.length === 0) {
      throw new Error('At least one parent is required when creating a student');
    }

    if (input.parents.length > 2) {
      throw new Error('Maximum two parents allowed per student');
    }

    // Get PARENT role
    const parentRole = await prisma.role.findFirst({
      where: { name: 'PARENT', schoolId: null },
    });

    if (!parentRole) {
      throw new Error('PARENT role not found in system');
    }

    // Create parent users and link them to the student
    for (const parentData of input.parents) {
      const parentUserId = randomUUID();
      const parentEmail = parentData.email || `parent.${parentUserId.substring(0, 8)}@${schoolId}.alenna.io`;

      // Check if parent email already exists
      const existingParent = await prisma.user.findUnique({
        where: { email: parentEmail },
      });

      let parentUser;
      if (existingParent) {
        // If parent already exists, use existing user
        parentUser = existingParent;
      } else {
        // Create new parent user
        parentUser = await prisma.user.create({
          data: {
            id: parentUserId,
            clerkId: `parent_${parentUserId}_clerk`, // Placeholder - will be set on first login
            email: parentEmail,
            firstName: parentData.firstName,
            lastName: parentData.lastName,
            schoolId,
          },
        });

        // Assign PARENT role if not already assigned
        const hasParentRole = await prisma.userRole.findFirst({
          where: {
            userId: parentUser.id,
            roleId: parentRole.id,
          },
        });

        if (!hasParentRole) {
          await prisma.userRole.create({
            data: {
              id: randomUUID(),
              userId: parentUser.id,
              roleId: parentRole.id,
            },
          });
        }
      }

      // Link parent to student
      const existingLink = await prisma.userStudent.findFirst({
        where: {
          userId: parentUser.id,
          studentId: createdStudent.id,
        },
      });

      if (!existingLink) {
        await prisma.userStudent.create({
          data: {
            id: randomUUID(),
            userId: parentUser.id,
            studentId: createdStudent.id,
            relationship: parentData.relationship || 'Parent',
          },
        });
      }
    }

    // 8. Return student with updated parents list
    const studentWithParents = await this.studentRepository.findById(createdStudent.id, schoolId);
    return studentWithParents || createdStudent;
  }
}

