import { IUserRepository } from '../../../adapters_interface/repositories';
import { User } from '../../../domain/entities';
import { SyncUserInput } from '../../dtos';

export class SyncUserUseCase {
  constructor(private userRepository: IUserRepository) {}

  async execute(input: SyncUserInput): Promise<User> {
    const { clerkId, email, firstName, lastName, schoolId } = input;

    // Check if user exists
    const existingUser = await this.userRepository.findByClerkId(clerkId);

    if (existingUser) {
      // Update existing user
      const updatedUser = existingUser.update({
        email,
        firstName: firstName || existingUser.firstName,
        lastName: lastName || existingUser.lastName,
      });

      return this.userRepository.update(existingUser.id, updatedUser);
    } else {
      // Create new user - require schoolId
      if (!schoolId) {
        throw new Error('School ID is required for new user registration');
      }

      const newUser = User.create({
        id: '', // Will be generated by database
        clerkId,
        email,
        schoolId,
        firstName,
        lastName,
        role: 'TEACHER',
      });

      return this.userRepository.create(newUser);
    }
  }
}

