import { ISchoolRepository } from '../../../adapters_interface/repositories';
import { School } from '../../../domain/entities';
import { CreateSchoolInput } from '../../dtos';

export class CreateSchoolUseCase {
  constructor(private schoolRepository: ISchoolRepository) {}

  async execute(input: CreateSchoolInput): Promise<School> {
    const school = School.create({
      id: '', // Will be generated by database
      name: input.name,
      address: input.address,
      phone: input.phone,
      email: input.email,
    });

    return this.schoolRepository.create(school);
  }
}

