import { ISchoolRepository } from '../../../adapters_interface/repositories';
import { School } from '../../../domain/entities';
import { CreateSchoolInput } from '../../dtos';
import { CreateDefaultTemplatesUseCase } from '../projection-templates/CreateDefaultTemplatesUseCase';
import { ProjectionTemplateRepository } from '../../../frameworks/database/repositories/ProjectionTemplateRepository';
import { EnableSchoolModuleUseCase } from '../modules/EnableSchoolModuleUseCase';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export class CreateSchoolUseCase {
  constructor(private schoolRepository: ISchoolRepository) {}

  async execute(input: CreateSchoolInput): Promise<School> {
    const school = School.create({
      id: '', // Will be generated by database
      name: input.name,
      address: input.address,
      phone: input.phone,
      email: input.email,
      teacherLimit: input.teacherLimit,
      userLimit: input.userLimit,
    });

    const createdSchool = await this.schoolRepository.create(school);

    // Setup module access for the new school
    // If moduleIds provided, only enable those modules; otherwise enable default modules
    try {
      if (input.moduleIds && input.moduleIds.length > 0) {
        await this.setupSelectedModules(createdSchool.id, input.moduleIds);
      } else {
        // Default behavior: enable standard modules (students, school_admin, groups)
        await this.setupModuleAccess(createdSchool.id);
      }
    } catch (error) {
      console.error('Error setting up module access for school:', error);
      // Don't fail school creation if module setup fails - it can be fixed manually
    }

    // Create default projection templates for this school
    try {
      const templateRepository = new ProjectionTemplateRepository();
      const createDefaultTemplatesUseCase = new CreateDefaultTemplatesUseCase(templateRepository);
      await createDefaultTemplatesUseCase.execute(createdSchool.id);
    } catch (error) {
      console.error('Error creating default templates for school:', error);
      // Don't fail school creation if templates fail - they can be created later
    }

    return createdSchool;
  }

  /**
   * Enable default modules for the school and grant role-module access
   * Default modules: students, school_admin, groups
   */
  private async setupModuleAccess(schoolId: string): Promise<void> {
    const enableModuleUseCase = new EnableSchoolModuleUseCase();
    
    // Default modules to enable for new schools
    const defaultModuleKeys = ['students', 'school_admin', 'groups'];
    
    for (const moduleKey of defaultModuleKeys) {
      const module = await prisma.module.findUnique({ where: { key: moduleKey } });
      if (module) {
        try {
          await enableModuleUseCase.execute(schoolId, module.id);
          console.log(`✅ Enabled ${moduleKey} module for school ${schoolId}`);
        } catch (error) {
          console.error(`❌ Error enabling ${moduleKey} module for school ${schoolId}:`, error);
          // Continue with other modules even if one fails
        }
      }
    }
  }

  /**
   * Enable only the selected modules for the school
   */
  private async setupSelectedModules(schoolId: string, moduleIds: string[]): Promise<void> {
    const enableModuleUseCase = new EnableSchoolModuleUseCase();
    
    for (const moduleId of moduleIds) {
      try {
        await enableModuleUseCase.execute(schoolId, moduleId);
        console.log(`✅ Enabled module ${moduleId} for school ${schoolId}`);
      } catch (error) {
        console.error(`❌ Error enabling module ${moduleId} for school ${schoolId}:`, error);
        // Continue with other modules even if one fails
      }
    }
  }
}

